export default function audio() {
  return [
    "ACOUSTIC AUDIO",
    "ADCOM",
    "AIWA",
    "AKAI",
    "ALTEC LANSING",
    "AMC",
    "ANTHEM",
    "APEX DIGITAL",
    "APPLE",
    "ARCAM",
    "AUDIO CONTROL",
    "AUDIO TECHNICA",
    "AUDIO ZENITH",
    "AUDIOENGINE",
    "AUDIOSOURCE",
    "AUDIOTRONIC",
    "AXESS",
    "BLACKWEB",
    "BOHM",
    "BOSE",
    "BOSTON ACOUSTIC",
    "BOWERS & WILKINS",
    "CALIFORNIA AUDIO LABS",
    "CAMBRIDGE AUDIO",
    "CARVER",
    "CASIO",
    "CENTRIOS",
    "CITIZEN",
    "COBY",
    "CRAIG",
    "CURTIS MATHES",
    "DEFINITIVE TECHNOLOGY",
    "DENON",
    "DURABRAND",
    "DYNEX",
    "EMERSON",
    "EMOTIVA",
    "ENCLAVE AUDIO",
    "FISHER",
    "FOCAL",
    "GENEXXA",
    "GOLDSTAR",
    "HARMAN/KARDON",
    "HITACHI",
    "ILIVE",
    "INKEL",
    "INNOVATIVE TECHNOLOGY",
    "INSIGNIA",
    "INTEGRA",
    "JBL",
    "JC PENNEY",
    "JVC",
    "KENWOOD",
    "KLIPSCH",
    "KODA",
    "KOSS",
    "KRELL",
    "KYOCERA",
    "LENOXX",
    "LG",
    "LINN",
    "LOGITECH",
    "LUXMAN",
    "LXI",
    "MAGNAVOX",
    "MARANTZ",
    "MARTIN LOGAN",
    "MCINTOSH",
    "MCS",
    "MICROMEGA",
    "MINT",
    "MISSION",
    "MITSUBISHI",
    "MONOPRICE",
    "MYRYAD",
    "NAD",
    "NAKAMICHI",
    "NEC",
    "NIKKO",
    "NORCENT",
    "NSM",
    "ONKYO",
    "ONN",
    "OPTIMUS",
    "OUTLAW",
    "PANASONIC",
    "PARADIGM",
    "PHILIPS",
    "PINNACLE SPEAKERS",
    "PIONEER",
    "POLK AUDIO",
    "PROFICIENT",
    "PROSCAN",
    "PROTON",
    "PYLE",
    "QED",
    "QUASAR",
    "RCA",
    "ROTEL",
    "SAMSUNG",
    "SANSUI",
    "SANYO",
    "SHARP",
    "SHERBOURN",
    "SHERWOOD",
    "SHURE",
    "SKYFI",
    "SONY",
    "SPEAKERCRAFT",
    "STEREOPHONIC",
    "STS",
    "SUNFIRE",
    "SYLVANIA",
    "SYMPHONIC",
    "TAO",
    "TEAC",
    "TECHNICS",
    "THETA DIGITAL",
    "THORENS",
    "TOSHIBA",
    "TRUAUDIO",
    "VENTURER",
    "VICTOR",
    "VIZIO",
    "VOXX",
    "YAMAHA",
    "ZENITH",
    "ZVOX"
  ];
}
