export default function bluray() {
  return [
    "ALLEGRO",
    "CINEVISION",
    "DAEWOO",
    "DENON",
    "DISNEY",
    "ELECTROHOME",
    "FUNAI",
    "GE",
    "GO VIDEO",
    "GOLDSTAR",
    "HARMAN KARDON",
    "HITACHI",
    "HP",
    "HUMAX",
    "INSIGNIA",
    "JBL",
    "JVC",
    "LG",
    "MAGNAVOX",
    "MARANTZ",
    "MEMOREX",
    "MITSUBISHI",
    "NEW ACOUSTIC DIMENSION",
    "ONKYO",
    "OPPO",
    "PANASONIC",
    "PHILIPS",
    "PIONEER",
    "PROSCAN",
    "RCA",
    "SAMSUNG",
    "SANYO",
    "SHARP",
    "SHERWOOD",
    "SONY",
    "SYLVANIA",
    "TCL",
    "TIVO",
    "TOSHIBA",
    "VIZIO",
    "YAMAHA",
    "ZENITH"
  ];
}
