export default function dvdplayer() {
  return [
    "ACESONIC",
    "AIWA",
    "AKAI",
    "ALLEGRO",
    "AMW",
    "APEX",
    "ASPIRE",
    "ASTAR",
    "AUDIOVOX",
    "AXION",
    "BLAUPUNKT",
    "BOSE",
    "BOSS",
    "BOSTON ACOUSTIC",
    "BROKSONIC",
    "CALIFORNIA AUDIO LABS",
    "CAVS",
    "CHANGHONG",
    "CINEVISION",
    "CITIZEN",
    "CLASSIC",
    "COBY",
    "CONTEL",
    "CRITERION",
    "CURTIS INTERNATIONAL",
    "CURTIS MATHES",
    "CYBERHOME",
    "DAEWOO",
    "DENON",
    "DESAY",
    "DIAMOND VISION",
    "DIGITREX",
    "DIGIX",
    "DISNEY",
    "DURABRAND",
    "DVD2000",
    "DYNEX",
    "ELTA",
    "EMERSON",
    "ESA",
    "FISHER",
    "FUNAI",
    "GE",
    "GO-VIDEO",
    "GOLDSTAR",
    "GPX",
    "HAIER",
    "HARMAN KARDON",
    "HD-DVD",
    "HELIOS",
    "HITACHI",
    "HITEKER",
    "HUMAX",
    "ILO",
    "INSIGNIA",
    "INTEGRA",
    "JBL",
    "JVC",
    "JWIN",
    "KAWASAKI",
    "KENWOOD",
    "KISS",
    "KLH",
    "KONKA",
    "KOSS",
    "LASONIC",
    "LENOXX",
    "LG",
    "LITEON",
    "LOGITECH",
    "MAGNAVOX",
    "MARANTZ",
    "MAXENT",
    "MEDION",
    "MEMOREX",
    "MERIDIAN",
    "MICROSOFT",
    "MINTEK",
    "MITSUBISHI",
    "MUSTEK",
    "MYRON & DAVIS",
    "NAD",
    "NAKAMICHI",
    "NEC",
    "NEXXTECH",
    "NORCENT",
    "ONKYO",
    "ONN",
    "OPTIMUS",
    "ORION",
    "ORITRON",
    "PANASONIC",
    "PHILCO",
    "PHILIPS",
    "PIONEER",
    "PIVA",
    "POLAROID",
    "POLK AUDIO",
    "PORTLAND",
    "POWER ACOUSTIK",
    "PROSCAN",
    "PROSONIC",
    "PROTRON",
    "PYLE",
    "RADIOSHACK",
    "RCA",
    "REGENT",
    "RJ TECHNOLOGY",
    "ROTEL",
    "SAMPO",
    "SAMSUNG",
    "SANSUI",
    "SANYO",
    "SHARP",
    "SHERWOOD",
    "SHINSONIC",
    "SONIC BLUE",
    "SONY",
    "SOUNDSTORM",
    "SPECTRONIQ",
    "SUNGALE",
    "SUPERSCAN",
    "SUPERSONIC",
    "SYLVANIA",
    "SYMPHONIC",
    "TASCAM",
    "TCL",
    "TEAC",
    "TECHNICS",
    "THETA DIGITAL",
    "TIVO",
    "TOSHIBA",
    "TRUTECH",
    "VIZIO",
    "WESTINGHOUSE",
    "XBOX",
    "YAMAHA",
    "YAMAKAWA",
    "ZENITH"
  ];
}
