export default function soundbar() {
  return [
    "ACOUSTIC AUDIO",
    "ALTEC LANSING",
    "AMC",
    "ARCAM",
    "AUDIOENGINE",
    "AUDIOSOURCE",
    "AUDIOVOX",
    "AXESS",
    "BLACKWEB",
    "BOHM",
    "BOSE",
    "BOSTON ACOUSTICS",
    "BOWERS & WILKINS",
    "CALIFORNIA AUDIO LABS",
    "CAMBRIDGE AUDIO",
    "COBY",
    "CRAIG",
    "CURTIS",
    "DEFINITIVE TECHNOLOGY",
    "DENON",
    "DYNEX",
    "EMOTIVA",
    "ENCLAVE AUDIO",
    "FOCAL",
    "HARMAN/KARDON",
    "ILIVE",
    "INNOVATIVE TECHNOLOGY",
    "INSIGNIA",
    "INTEGRA",
    "JBL",
    "JVC",
    "KENWOOD",
    "KLIPSCH",
    "LENOXX",
    "LG",
    "MAGNAVOX",
    "MARANTZ",
    "MARTIN LOGAN",
    "MAXELL",
    "MCINTOSH",
    "MINT",
    "MONOPRICE",
    "NAD",
    "ONKYO",
    "ONN",
    "PANASONIC",
    "PARADIGM",
    "PHILIPS",
    "PINNACLE SPEAKERS",
    "PIONEER",
    "POLK AUDIO",
    "PROFICIENT",
    "PROSCAN",
    "PYLE",
    "RCA",
    "ROTEL",
    "SAMSUNG",
    "SANSUI",
    "SANYO",
    "SHARP",
    "SHERBOURN",
    "SHERWOOD",
    "SONOS",
    "SONY",
    "SPEAKERCRAFT",
    "SUNFIRE",
    "SYLVANIA",
    "TEAC",
    "TECHNICS",
    "TOSHIBA",
    "TRUAUDIO",
    "VIZIO",
    "YAMAHA",
    "ZENITH",
    "ZVOX"
  ];
}
